"""Render every layout of a template pack with its example content.

Writes <pack>/thumbnails/<id>.png and docs/layouts-<pack-id>.md. Needs LibreOffice and poppler.
Run: uv run python scripts/build_thumbnails.py [--template ID]
"""

from __future__ import annotations

import argparse
import shutil
import tempfile
from pathlib import Path

from deckwright import pack
from deckwright.deck import build_deck
from deckwright.models import DeckSpec
from deckwright.pack import EXAMPLE_IMAGE
from deckwright.render import to_pngs

ROOT = Path(__file__).resolve().parents[1]
SAMPLE = str(ROOT / "examples" / "assets" / "landscape.jpg")


def _sub(v):
    if v == EXAMPLE_IMAGE:
        return SAMPLE
    if isinstance(v, dict):
        return {k: _sub(x) for k, x in v.items()}
    if isinstance(v, list):
        return [_sub(x) for x in v]
    return v


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", default="sample", help="pack id; default: sample")
    args = ap.parse_args()

    template = pack.load(args.template)
    layouts = template.layouts
    spec = DeckSpec(template=template.id, slides=[{"layout": l.id, **_sub(l.example)} for l in layouts])
    result = build_deck(spec, template)

    thumbs = template.thumbnails
    thumbs.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        deck = Path(tmp) / "catalog.pptx"
        deck.write_bytes(result.data)
        pngs = to_pngs(deck, Path(tmp) / "png", dpi=36, fonts=template.fonts)
        for layout, png in zip(layouts, pngs):
            shutil.copy(png, thumbs / f"{layout.id}.png")

    doc = ROOT / "docs" / f"layouts-{template.id}.md"
    lines = [
        "# Layout catalog",
        "",
        f"Generated by `scripts/build_thumbnails.py --template {template.id}`. "
        "Each image shows the layout filled with its `example` content.",
        "",
    ]
    kind = None
    for l in layouts:
        if l.kind != kind:
            kind = l.kind
            lines += [f"## Kind: `{kind}`", ""]
        src = f"slide {l.ref}" if l.source == "slide" else f"master layout {l.ref}"
        fields = ", ".join(f"`{f.name}`" + ("*" if f.required else "") for f in l.fields) or "none"
        lines += [f"### `{l.id}`: {l.name}", "", f"![{l.id}](../{thumbs.relative_to(ROOT)}/{l.id}.png)", "",
                  l.description, "", f"- Use when: {l.use_when}", f"- Source: {src}", f"- Fields: {fields}"]
        if l.items:
            lines.append(f"- Items: {l.items.min} to {l.items.max}, fields "
                         + ", ".join(f"`{n}`" for n in l.items.fields))
        if l.aliases:
            lines.append(f"- Also selected for kind: {', '.join(f'`{a}`' for a in l.aliases)}")
        lines.append("")
    doc.parent.mkdir(parents=True, exist_ok=True)
    doc.write_text("\n".join(lines))
    print(f"wrote {len(layouts)} thumbnails and {doc}")


if __name__ == "__main__":
    main()
